# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/sota-image-classification',
                'doc_host': 'https://2catycm.github.io',
                'git_url': 'https://github.com/2catycm/sota-image-classification',
                'lib_path': 'sota_image_classification'},
  'syms': { 'sota_image_classification.core': { 'sota_image_classification.core.foo': ( 'core.html#foo',
                                                                                        'sota_image_classification/core.py')}}}
